# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2354faadfdfb54a075be6344e0f14a8b830d3bbaa30fa1ab73b167d85e6b346255b97f5a210984c68012063e2bf990a7e79a06438c590ecb6374cfcbefef8235

test:
  secret_key_base: dde62d909de8f7a155b5ccd6031143a89e88516b291430629795f6733171ccc8be322e2c768198fdb53b6a8de3a5bc5dfee4269401a5989cc1b40f37c745b5a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
